
utils.jsLoader.load(["firebugx.js","tile.1.js","tileshop_pmc.1/scale_pmc.1.js"]);function TileShop(){this.oTexts={sTitle:"Drag image to reposition. Double click to magnify further.",sTitleUp:"Drag image to reposition.",sTitleDown:"Click on image to magnify.",sTitleWait:"Wait...",sPanoramaTitle:"Click to change focus to this area of image.",sPanTitle:"Drag to focus on a different part of image.",sCloseButton:"Return to standard image view."};}
TileShop.prototype.Init=function(e){var oThis=this;this.oNotifier=new Notifier();var oTargetImg;var x,y;var sMode="";if(e.tagName=="IMG"){oTargetImg=e;x=1;y=1;sMode="inline";var s=document.location.href.split("?");if(s[1]){var a=utils.getParams(s[1]);oTargetImg.setAttribute("rel",encodeURI("/corecgi/tileshop/tileshop.fcgi?p="+a["p"]+"&id="+a["id"]));document.title=(a["title"]?a["title"]:"");}}else{oTargetImg=utils.getTargetObj(e);var oScroll=utils.getScrolls();var oDim=utils.getXY(oTargetImg);x=parseInt((oScroll.x+e.clientX-oDim.x)/oDim.w*100);y=parseInt((oScroll.y+e.clientY-oDim.y)/oDim.h*100);}
var rel=oTargetImg.getAttribute("rel");if(rel&&rel!=""){oTargetImg.setAttribute("rel",rel+"&x="+x+"&y="+y);}else{var src=oTargetImg.getAttribute("src");oTargetImg.setAttribute("src",src+"&x="+x+"&y="+y);}
var oDt=utils.getParent(oTargetImg);var oDl=utils.getParent(oDt);var oDiv=utils.getParent(oDl);var oTitlePanel=utils.getFirstChild(oDiv);var oTitleBar=utils.getFirstChild(oTitlePanel);var oCloseButton=utils.getNextSibling(oTitleBar);oCloseButton.title=this.oTexts.sCloseButton;if(sMode=="inline"){oCloseButton.style.visibility="hidden";}
var oScalePanel=utils.getFirstChild(oDl);var oTilePanel=utils.getNextSibling(oScalePanel);var oScalePanelW=48;var iTitleBarH=oTitlePanel.offsetHeight;oDt.style.position="relative";var sTitleBar=oTitleBar.innerHTML;oTitleBar.innerHTML=this.oTexts.sTitleWait;var oScaleCtrl,oPanoramaSwitcher,oPanorama,oTileData;var bClosing=false;oThis.oNotifier.setListener(this,"close",function(){bClosing=true;if(!oThis.oTile)return;if(sMode=="inline"){return;}
utils.removeChildren(oThis.oTile.oCanvas);oTilePanel.removeChild(oThis.oTile.oCanvas);utils.removeChildren(oPanoramaSwitcher.oCanvas);oDt.removeChild(oPanoramaSwitcher.oCanvas);oPanoramaSwitcher.oCanvas=null;utils.removeChildren(oPanorama.oCanvas);oDt.removeChild(oPanorama.oCanvas);utils.removeChildren(oScaleCtrl.oCanvas);oScalePanel.removeChild(oScaleCtrl.oCanvas);oThis.oTile.oCanvas=null;oPanorama.oCanvas=null;oScaleCtrl.oCanvas=null;oThis.oTile=null;oPanorama=null;oPanoramaSwitcher=null;oScaleCtrl=null;oTargetImg.style.display="block";oCloseButton.className="";oTitlePanel.className="";oScalePanel.className="";oScalePanel.style.width="0px";oTilePanel.style.width="auto";oTilePanel.style.height="auto";oDl.style.height="auto";oScalePanel.style.height="auto";oDiv.style.width=oTargetImg.offsetWidth+"px";oDiv.style.height="auto";oTitleBar.innerHTML=sTitleBar;},null);this.oNotifier.setListener(this,"resize-canvas",function(xx,bFlag){if(bClosing)return;var kW=0.9;var kH=0.7;if(sMode=="inline"){kW=0.98;kH=0.98;}
var minW=400;var minH=300;var oDimW=utils.getWindowDim();var W=parseInt(kW*oDimW.w);var H=parseInt(kH*oDimW.h);if(W<minW)W=minW;if(H<minH)H=minH;var oTilePanelW=W-oScalePanelW;var oTilePanelH=H-iTitleBarH;oDiv.style.width=W+"px";oDiv.style.height=H+"px";oTilePanel.style.width=oTilePanelW+"px";oTilePanel.style.height=oTilePanelH+"px";oTilePanel.style.overflow="hidden";oScalePanel.style.width=oScalePanelW+"px";oScalePanel.style.height=oTilePanelH+"px";if(bFlag){oThis.oNotifier.Notify(oThis,"resize",{w:oTilePanelW,h:oTilePanelH});}},null);this.oNotifier.setListener(oThis,"picture-is-drawn",function(){oTitlePanel.className="active";oCloseButton.className="active";oScalePanel.className="active";utils.addEvent(oCloseButton,"click",function(e){oThis.oNotifier.Notify(this,"close","");});});oThis.oNotifier.setListener(oThis,"disable",function(xx,oComment){if(oComment=="scale-up"){oTitleBar.innerHTML=oThis.oTexts.sTitleUp;}else if(oComment=="scale-down"){oTitleBar.innerHTML=oThis.oTexts.sTitleDown;}else{oTitleBar.innerHTML=oThis.oTexts.sTitle;}});oThis.oNotifier.Notify(this,"resize-canvas",false);var oImgForTiler=oTargetImg.cloneNode(false);oImgForTiler.width=oTargetImg.offsetWidth;oImgForTiler.height=oTargetImg.offsetHeight;oImgForTiler.setAttribute("title",this.oTexts.sPanoramaTitle);oTargetImg.style.display="none";if(utils.bIsTouchable){var elMsg=document.getElementById("msg");var d=0;var x,y;var b=true;utils.addEvent(oTilePanel,"touchstart",t_start);function t_start(e){var elTarget=utils.getTargetObj(e);if(e.touches.length!=2||(!utils.hasClass(elTarget.parentNode,"dnd")&&!utils.hasClass(elTarget.parentNode,"viewport-static-image")))return false;d=Math.pow((e.touches[0].clientX-e.touches[1].clientX),2)
+Math.pow((e.touches[0].clientY-e.touches[1].clientY),2);b=true;x=y=0;utils.addEvent(oTilePanel,"touchmove",t_move);}
function t_move(e){if(e.touches.length!=2)return false;x=e.touches[0].clientX-e.touches[1].clientX;y=e.touches[0].clientY-e.touches[1].clientY;if(b){utils.addEvent(oTilePanel,"touchend",t_end);b=false;}}
function t_end(e){utils.removeEvent(oTilePanel,"touchmove",t_move,false);if(x==0&&y==0)return false;var D=x*x+y*y-d;var n=10000;if(D>n)oScaleCtrl.oCanvas.oSelected.iScaleIndex--;else if(D<-n)oScaleCtrl.oCanvas.oSelected.iScaleIndex++;if(s)oThis.oNotifier.Notify(this,"scale",oScaleCtrl.oCanvas.oSelected.iScaleIndex);x=y=0;}}
setTimeout(function(){oTileData=new TileDataDb(oImgForTiler,oThis.oNotifier);oTileData.oViewport.w=parseInt(oTilePanel.style.width);oTileData.oViewport.h=parseInt(oTilePanel.style.height);oTileData.oViewport.x=0;oTileData.oViewport.y=0;oThis.oTile=new Tile(oTileData,oThis.oNotifier);oTilePanel.appendChild(oThis.oTile.oCanvas);oPanorama=new Panorama(oTileData,oThis.oNotifier);oPanorama.oCanvas.style.zIndex=100;oPanorama.oPan.oCanvas.setAttribute("title",oThis.oTexts.sPanTitle);oTilePanel.appendChild(oPanorama.oCanvas);oPanoramaSwitcher=new PanoramaSwitcher(oTileData,oThis.oNotifier);oPanoramaSwitcher.oCanvas.style.zIndex=oPanorama.oCanvas.style.zIndex+1;oTilePanel.appendChild(oPanoramaSwitcher.oCanvas);oScaleCtrl=new ScaleCtrl(oTileData,oThis.oNotifier);oScalePanel.appendChild(oScaleCtrl.oCanvas);oThis.oNotifier.Notify(this,"resize-canvas",true);},100);}
TileShop.Load=function(sClassName){utils.addEvent(window,"load",function(){oTileshop=$C(sClassName);for(var i in oTileshop){if(utils.hasClass(oTileshop[i],"open")){oTileshop[i].oApp=new TileShop();oTileshop[i].oApp.Init(oTileshop[i]);}else{utils.addEvent(oTileshop[i],"click",function(e){oTileshop[i].oApp=new TileShop();oTileshop[i].oApp.Init(e);});}}
utils.addEvent(window,"resize",function(e){for(var i in oTileshop){if(oTileshop[i].oApp&&oTileshop[i].oApp.oTile){oTileshop[i].oApp.oNotifier.Notify(oTileshop[i],"resize-canvas",true);}}});});}
TileShop.Load("tileshop");